version: '3.7'
services:
  client:
    environment:
      - GET_HOSTS_FROM=dns
      - CLIENT_NAME=${CLIENT_NAME_BASE}1
      - FEDN_MINIO_HOST=${FEDN_MINIO_HOST}
      - FEDN_MINIO_PORT=${FEDN_MINIO_PORT}
      - FEDN_MINIO_ACCESS_KEY=${FEDN_MINIO_ACCESS_KEY}
      - FEDN_MINIO_SECRET_KEY=${FEDN_MINIO_SECRET_KEY}
    image: "scaleoutsystems/client:latest"
    # NOTE: if working on a remote host then you can override dns mapping like this:
    #extra_hosts:
    #  reducer: ${FEDN_HOST}
    #  combiner: ${FEDN_HOST}
    #  combiner2: ${FEDN_HOST}
    #  combiner3: ${FEDN_HOST}
    build:
      context: .
      dockerfile: components/client/Dockerfile
    working_dir: /app/
    command: /bin/bash -c "fedn run client -d ${FEDN_REDUCER_HOST} -p ${FEDN_REDUCER_PORT} -t ${FEDN_ALLIANCE_ADMIN_AUTH_TOKEN}"
    volumes:
      - ./test/${EXAMPLE}/data:/app/data