version: '3.3'

services:

  combiner:
    image: "scaleoutsystems/fedn-client:latest"
    environment:
      - PYTHONUNBUFFERED=0
      - GET_HOSTS_FROM=dns
    build:
      context: .
      dockerfile: components/client/Dockerfile
    working_dir: /app/client
    command: sh -c "sleep 5 && fedn run combiner -in ./config/settings-combiner.yaml"
    volumes:
      - ./config:/app/client/config
      - ./tmp/c1-models:/tmp/models
    ports:
      - 12080:12080
