version: '3.7'

services:
  
  combiner:
    environment:
      - GET_HOSTS_FROM=dns
      - ALLIANCE_UID=${ALLIANCE_UID}
      - FEDN_MINIO_HOST=${FEDN_MINIO_HOST}
      - FEDN_MINIO_PORT=${FEDN_MINIO_PORT}
      - FEDN_MINIO_ACCESS_KEY=${FEDN_MINIO_ACCESS_KEY}
      - FEDN_MINIO_SECRET_KEY=${FEDN_MINIO_SECRET_KEY}
    image: "scaleoutsystems/client:latest"
    build:
      context: .
      dockerfile: components/client/Dockerfile
    working_dir: /app/client
    command: fedn run combiner -d ${FEDN_REDUCER_HOST} -p ${FEDN_REDUCER_PORT} -t ${FEDN_ALLIANCE_ADMIN_AUTH_TOKEN} -h combiner -i 12080 -n combiner
    volumes:
      - ./test/${EXAMPLE}/combiner:/app/client
    ports:
        - 12080:12080

  monitor:
    image: "scaleoutsystems/monitor:latest"
    build:
      context: .
      dockerfile: components/monitor/Dockerfile
    environment:
      - GET_HOSTS_FROM=dns
      - MONITOR_HOST=combiner
      - MONITOR_PORT=12080
      - USER=test
      - PROJECT=project
      - ALLIANCE_UID=${ALLIANCE_UID}
      - MONGO_HOST=${FEDN_MONGO_HOST}
      - MONGO_PORT=${FEDN_MONGO_PORT}
      - MDBUSR=${FEDN_MONGO_USER}
      - MDBPWD=${FEDN_MONGO_PASSWORD} 
    working_dir: /app/
    command: bash run.sh
    #volumes:
    #  - ./components/monitor/:/app/
    depends_on:
      - combiner
