version: '3.3'

services:

  combiner:
    image: "scaleoutsystems/fedn-client:latest"
    environment:
      - PYTHONUNBUFFERED=0
      - GET_HOSTS_FROM=dns
    build:
      context: .
      dockerfile: components/client/Dockerfile
    working_dir: /app/client
    command: fedn run combiner -in ./config/settings-combiner.yaml 
    volumes:
      - ./tmp/c1-models:/tmp/models
    ports:
      - 12080:12080

  combiner2:
    environment:
      - PYTHONUNBUFFERED=0
      - GET_HOSTS_FROM=dns
      - ALLIANCE_UID=${ALLIANCE_UID}
      - FEDN_MINIO_HOST=${FEDN_MINIO_HOST}
      - FEDN_MINIO_PORT=${FEDN_MINIO_PORT}
      - FEDN_MINIO_ACCESS_KEY=${FEDN_MINIO_ACCESS_KEY}
      - FEDN_MINIO_SECRET_KEY=${FEDN_MINIO_SECRET_KEY}
      - FEDN_MONGO_USER=${FEDN_MONGO_USER}
      - FEDN_MONGO_PASSWORD=${FEDN_MONGO_PASSWORD}
      - FEDN_MONGO_HOST=${FEDN_MONGO_HOST}
      - FEDN_MONGO_PORT=${FEDN_MONGO_PORT}
    image: "scaleoutsystems/client:latest"
    build:
      context: .
      dockerfile: components/client/Dockerfile
    working_dir: /app/client
    command: fedn run combiner -d ${FEDN_REDUCER_HOST} -p ${FEDN_REDUCER_PORT} -t ${FEDN_ALLIANCE_ADMIN_AUTH_TOKEN} -h combiner2 -i 12081 -n combiner2
    volumes:
      - ./tmp/c2-models:/tmp/models
    ports:
      - 12081:12081
