version: '3.7'

services:

  client1:
    environment:
      - GET_HOSTS_FROM=dns
      - CLIENT_NAME=${CLIENT_NAME_BASE}1
    image: "scaleoutsystems/client:latest"
    build:
      context: .
      dockerfile: components/client/Dockerfile
    working_dir: /app/client
    command: /bin/bash -c "sleep 10 && fedn run client -d ${FEDN_CONTROLLER_HOST} -p ${FEDN_CONTROLLER_PORT} -n ${CLIENT_NAME_BASE}1  -i ${FEDN_CLIENT_ID} -t ${FEDN_ALLIANCE_ADMIN_AUTH_TOKEN}" 
    volumes:
      - ./test/${EXAMPLE}/client:/app/client
      - ./test/${EXAMPLE}/data:/app/data

  client2:
    environment:
      - GET_HOSTS_FROM=dns
      - CLIENT_NAME=${CLIENT_NAME_BASE}2
    image: "scaleoutsystems/client:latest"
    build:
      context: .
      dockerfile: components/client/Dockerfile
    working_dir: /app/client
    command: /bin/bash -c "sleep 10 && fedn run client -d ${FEDN_CONTROLLER_HOST} -p ${FEDN_CONTROLLER_PORT} -n ${CLIENT_NAME_BASE}2 -i ${FEDN_CLIENT_ID} -t ${FEDN_ALLIANCE_ADMIN_AUTH_TOKEN}"
    volumes:
      - ./test/${EXAMPLE}/client:/app/client
      - ./test/${EXAMPLE}/data:/app/data

  client3:
    environment:
      - GET_HOSTS_FROM=dns
      - CLIENT_NAME=${CLIENT_NAME_BASE}3
    image: "scaleoutsystems/client:latest"
    build:
      context: .
      dockerfile: components/client/Dockerfile
    working_dir: /app/client
    command: /bin/bash -c "sleep 10 && fedn run client -d ${FEDN_CONTROLLER_HOST} -p ${FEDN_CONTROLLER_PORT} -n ${CLIENT_NAME_BASE}3 -i ${FEDN_CLIENT_ID} -t ${FEDN_ALLIANCE_ADMIN_AUTH_TOKEN}"
    volumes:
      - ./test/${EXAMPLE}/client:/app/client
      - ./test/${EXAMPLE}/data:/app/data
    ports:
      - 8090:8090

  client4:
    environment:
      - GET_HOSTS_FROM=dns
      - CLIENT_NAME=${CLIENT_NAME_BASE}4
    image: "scaleoutsystems/client:latest"
    build:
      context: .
      dockerfile: components/client/Dockerfile
    working_dir: /app/client
    command: /bin/bash -c "sleep 10 && fedn run client -d ${FEDN_CONTROLLER_HOST} -p ${FEDN_CONTROLLER_PORT} -n ${CLIENT_NAME_BASE}4 -i ${FEDN_CLIENT_ID} -t ${FEDN_ALLIANCE_ADMIN_AUTH_TOKEN}"
    volumes:
      - ./test/${EXAMPLE}/client:/app/client
      - ./test/${EXAMPLE}/data:/app/data

  client5:
    environment:
      - GET_HOSTS_FROM=dns
      - CLIENT_NAME=${CLIENT_NAME_BASE}5
    image: "scaleoutsystems/client:latest"
    build:
      context: .
      dockerfile: components/client/Dockerfile
    working_dir: /app/client
    command: /bin/bash -c "sleep 10 && fedn run client -d ${FEDN_CONTROLLER_HOST} -p ${FEDN_CONTROLLER_PORT} -n ${CLIENT_NAME_BASE}5 -i ${FEDN_CLIENT_ID} -t ${FEDN_ALLIANCE_ADMIN_AUTH_TOKEN}"
    volumes:
      - ./test/${EXAMPLE}/client:/app/client
      - ./test/${EXAMPLE}/data:/app/data
