version: '3.7'

services:

  reducer:
    environment:
      - GET_HOSTS_FROM=dns
      - ALLIANCE_UID=${ALLIANCE_UID}
      - USER=test
      - PROJECT=project
      - MONGO_HOST=${FEDN_MONGO_HOST}
      - MONGO_PORT=${FEDN_MONGO_PORT}
      - MDBUSR=${MDBUSR}
      - MDBPWD=${MDBPWD} 
    image: "scaleoutsystems/client:latest"
    build:
      context: .
      dockerfile: components/client/Dockerfile
    working_dir: /app/client
    command: fedn run reducer -t ${FEDN_ALLIANCE_ADMIN_AUTH_TOKEN} -n reducer
    volumes:
      - ./test/${EXAMPLE}/reducer:/app/client
    ports:
        - 8090:8090