version: '3.7'

services:

  reducer:
    environment:
      - GET_HOSTS_FROM=dns
      - ALLIANCE_UID=${ALLIANCE_UID}
      - USER=test
      - PROJECT=project
      - MONGO_HOST=${FEDN_MONGO_HOST}
      - MONGO_PORT=${FEDN_MONGO_PORT}
      - MDBUSR=${MDBUSR}
      - MDBPWD=${MDBPWD} 
    image: "scaleoutsystems/client:latest"
    build:
      context: .
      dockerfile: components/client/Dockerfile
    working_dir: /app/client
    #command: "sh -c 'sleep 10 && fedn run reducer'"
    command: ./run.sh
    volumes:
      - ./test/${EXAMPLE}/reducer:/app/client
    #  - ./fedn:/app/fedn
    #  - ./cli:/app/cli
    ports:
        - 8090:8090