version: '3.7'

services:

  reducer:
    environment:
      - GET_HOSTS_FROM=dns
      - ALLIANCE_UID=${ALLIANCE_UID}
      - USER=test
      - PROJECT=project
      - MONGO_HOST=${FEDN_MONGO_HOST}
      - MONGO_PORT=${FEDN_MONGO_PORT}
      - MDBUSR=${FEDN_MONGO_USER}
      - MDBPWD=${FEDN_MONGO_PASSWORD} 
    image: "scaleoutsystems/client:latest"
    build:
      context: .
      dockerfile: components/client/Dockerfile
    working_dir: /app/client
    command: sh -c "mkdir -p /app/client/certs && fedn run reducer -n reducer -t ${FEDN_ALLIANCE_ADMIN_AUTH_TOKEN}"
    volumes:
      - ./test/${EXAMPLE}/reducer:/app/client
    ports:
        - 8090:8090