version: '3.7'

services:
  
  seed:
    environment:
      - GET_HOSTS_FROM=dns
      - ALLIANCE_UID=${ALLIANCE_UID}
    image: "scaleoutsystems/client:latest"
    build:
      context: .
      dockerfile: components/client/Dockerfile
    working_dir: /app/client
    command: ./seed.sh
    volumes:
      - ./test/${EXAMPLE}/seed:/app/client
    # - ./fedn:/app/fedn
    # - ./cli:/app/cli
    #ports:
    #    - 12080:12080
